imports:
    - php
 
filter:
    excluded_paths: [test/*]
 
tools:
    external_code_coverage: true

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
